/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mcqapp;

import com.mysql.jdbc.PreparedStatement;
import java.security.SecureRandom;
import java.sql.Connection;

import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sujal
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        lbl_q1.setText("");
        lbl_q2.setText("");
        lbl_q3.setText("");
        lbl_q4.setText("");
        lbl_ca.setText("");
        lbl_question.setText("");
        btn_delete.setVisible(false);
        q_id.setVisible(false);
        btn_questionsDelete.setVisible(false);
        setResizable(false);
        
        load_data();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    String update_username = "";
    int q_no;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fname = new javax.swing.JTextField();
        txt_std_id = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_users = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        question = new javax.swing.JTextField();
        q1 = new javax.swing.JTextField();
        q2 = new javax.swing.JTextField();
        q3 = new javax.swing.JTextField();
        q4 = new javax.swing.JTextField();
        ca = new javax.swing.JTextField();
        btn_questionAdd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_q1 = new javax.swing.JLabel();
        lbl_q2 = new javax.swing.JLabel();
        lbl_q3 = new javax.swing.JLabel();
        lbl_q4 = new javax.swing.JLabel();
        lbl_ca = new javax.swing.JLabel();
        lbl_question = new javax.swing.JLabel();
        subject = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_questions = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_batch = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_section = new javax.swing.JTextField();
        lbl_name = new javax.swing.JLabel();
        lbl_std_id = new javax.swing.JLabel();
        lbl_batch = new javax.swing.JLabel();
        lbl_section = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        btn_questionsDelete = new javax.swing.JButton();
        q_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_register.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        tbl_users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "std_name", "std_id", "batch", "section", "username", "password"
            }
        ));
        tbl_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_usersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_users);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Add User");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Add Question");

        btn_questionAdd.setText("Add Question");
        btn_questionAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_questionAddActionPerformed(evt);
            }
        });

        jLabel3.setText("Option 1");

        jLabel4.setText("Option 3");

        jLabel5.setText("Option 2");

        jLabel6.setText("Option 4");

        jLabel7.setText("Correct");

        lbl_q1.setText("jLabel8");

        lbl_q2.setText("jLabel9");

        lbl_q3.setText("jLabel10");

        lbl_q4.setText("jLabel11");

        lbl_ca.setText("jLabel12");

        lbl_question.setText("jLabel8");

        subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "History", "General Knowledge", "Science" }));

        jLabel8.setText("Subject");

        tbl_questions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Question", "Option 1", "Option 2", "Option 3", "Option 4", "Correct Answer", "Subject", "question_no"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_questions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_questionsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_questions);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Name");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Student Id");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Batch");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setText("Section");

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_questionsDelete.setText("Delete");
        btn_questionsDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_questionsDeleteActionPerformed(evt);
            }
        });

        q_id.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(txt_std_id, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lbl_std_id, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_batch, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_batch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel12)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_section, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_section, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btn_delete)))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lbl_question))
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(q_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel3)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_q1))
                .addGap(61, 61, 61)
                .addComponent(jLabel4)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_q3)
                    .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ca, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ca))
                .addGap(98, 98, 98)
                .addComponent(btn_questionAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel5)
                .addGap(22, 22, 22)
                .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel6)
                .addGap(22, 22, 22)
                .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btn_questionsDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(lbl_q2)
                .addGap(159, 159, 159)
                .addComponent(lbl_q4))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel10))
                            .addComponent(txt_std_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(lbl_std_id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txt_batch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lbl_batch, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lbl_section, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_section, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_register)
                            .addComponent(btn_delete)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lbl_question)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbl_q1))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbl_q3))
                    .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(ca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbl_ca))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_questionAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_questionsDelete))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_q2)
                    .addComponent(lbl_q4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:
        try{
            clearLabel();
            if(validation_user())
            {
                Connection dbconn = DBconnection.connection();
                PreparedStatement check = (PreparedStatement) dbconn.prepareStatement("select * from users where std_id = ?");
                check.setString(1,txt_std_id.getText());
                ResultSet chk = check.executeQuery();

                if(chk.next())
                {
                    JOptionPane.showMessageDialog(null,"Student ID already Exists");
                }
                else
                {
                if(btn_register.getText() == "Register"){
                String query = "INSERT INTO `users`(`username`,`password`,`std_name`, `std_id`, `batch`, `section`) VALUES (?,?,?,?,?,?)";
                PreparedStatement pst = (PreparedStatement) dbconn.prepareStatement(query);
        
                String username = generateToken(fname.getText());
                pst.setString(1,username);
                pst.setString(2,generateToken(username));
                pst.setString(3,fname.getText());
                pst.setString(4,txt_std_id.getText());
                pst.setString(5,txt_batch.getText());
                pst.setString(6,txt_section.getText());
                pst.executeUpdate();
                dbconn.close();
                JOptionPane.showMessageDialog(null,"Successfully Registered");
                dispose();
                Dashboard db = new Dashboard();
                db.setVisible(true);
                }
                
                else if(btn_register.getText()=="Update")
                {
                    
                    dbconn = DBconnection.connection();
                    PreparedStatement pst = (PreparedStatement) dbconn.prepareStatement("UPDATE `users` SET `std_name`=?,`std_id`= ?,`batch`=?,`section`=? WHERE username = ?");
                    pst.setString(1,fname.getText());
                    pst.setString(2,txt_std_id.getText());
                    pst.setString(3,txt_batch.getText());
                    pst.setString(4,txt_section.getText());
                    pst.setString(5,update_username);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Successfully Upated");
                    dispose();
                    new Dashboard().setVisible(true);
                    
                }
        
            }
        
        }
        }
        catch(SQLException e)
        {
            
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_btn_registerActionPerformed

        protected static SecureRandom random = new SecureRandom();
        
        public synchronized String generateToken( String username ) {
                long longToken = Math.abs( random.nextLong());
                String random = Long.toString( longToken, 32 );
                return (random );
        }
        
    public void load_data()
    {
        try{
        Connection dbconn = DBconnection.connection();
        String query = "select * from questions";
        PreparedStatement pst = (PreparedStatement) dbconn.prepareStatement(query);
        ResultSet result = pst.executeQuery();
        
        DefaultTableModel model = (DefaultTableModel) tbl_questions.getModel();
        model.setRowCount(0);
        
        while(result.next())
        {
            Object o[] = {result.getString("question"),result.getString("q1"),result.getString("q2"),result.getString("q3"),result.getString("q4"),result.getString("ca"),result.getString("Subject"),result.getString("question_no")};
            model.addRow(o);
        }
        
        }
        catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null,e);
                }
        
        try{
          Connection dbconn = DBconnection.connection();
        String query = "select * from users";
        PreparedStatement pst = (PreparedStatement) dbconn.prepareStatement(query);
        ResultSet result = pst.executeQuery();
        
        DefaultTableModel model = (DefaultTableModel) tbl_users.getModel();
        model.setRowCount(0);
        
        while(result.next())
        {
            Object o[] = {result.getString("std_name"),result.getString("std_id"),result.getString("batch"),result.getString("section"),result.getString("username"),result.getString("password")};
            model.addRow(o);
        }
        }
        catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null,e);
                }
        
        
        
    }
    
    private void btn_questionAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_questionAddActionPerformed
        // TODO add your handling code here:
        
        try{
            clearLabel();
           if(validation(question.getText(),q1.getText(),q2.getText(),q3.getText(),q4.getText(),ca.getText())){
               if(btn_questionAdd.getText() == "Add Question")
               {
            Connection dbconn = DBconnection.connection();
            
            String query = "INSERT INTO `questions`(`question`, `q1`, `q2`, `q3`, `q4`, `ca`,`subject`) VALUES (?,?,?,?,?,?,?)";
            PreparedStatement pst = (PreparedStatement) dbconn.prepareStatement(query);
            pst.setString(1,question.getText());
            pst.setString(2,q1.getText());
            pst.setString(3,q2.getText());
            pst.setString(4,q3.getText());
            pst.setString(5,q4.getText());
            pst.setString(6,ca.getText());
            String sub = subject.getSelectedItem().toString();
            pst.setString(7,sub);
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Succesfully Entered Question");
            Dashboard db = new Dashboard();
            dispose();
            db.setVisible(true);
            dbconn.close();
               }
               else if(btn_questionAdd.getText() == "Update")
               {
                    Connection dbconn = DBconnection.connection();
                    PreparedStatement pst = (PreparedStatement) dbconn.prepareStatement("UPDATE `questions` SET question=?,q1= ?,q2=?,q3=?, q4=?, ca = ?,subject = ? WHERE question_no = ?");
                    pst.setString(1,question.getText());
                    pst.setString(2,q1.getText());
                    pst.setString(3,q2.getText());
                    pst.setString(4,q3.getText());
                    pst.setString(5,q4.getText());
                    pst.setString(6,ca.getText());
                    pst.setString(7,subject.getSelectedItem().toString());
                    pst.setString(8,q_id.getText());
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Successfully Updated");
                    dispose();
                    new Dashboard().setVisible(true);
               }
               
           }

        }
        catch(SQLException e)
        {
            
            JOptionPane.showMessageDialog(null,e);
            
        }
        
    }//GEN-LAST:event_btn_questionAddActionPerformed

    private void tbl_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_usersMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbl_users.getModel();
                    int i = tbl_users.getSelectedRow();
            
            fname.setText(model.getValueAt(i, 0).toString());
            txt_std_id.setText(model.getValueAt(i, 1).toString());
            txt_batch.setText(model.getValueAt(i, 2).toString());
            txt_section.setText(model.getValueAt(i, 3).toString());
            update_username = (model.getValueAt(i,4).toString());
            
            btn_register.setText("Update");
            btn_delete.setVisible(true);
        
    }//GEN-LAST:event_tbl_usersMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        try{
        Connection dbconn = DBconnection.connection();
        PreparedStatement pst = (PreparedStatement) dbconn.prepareStatement("delete from users where username = ?");
        pst.setString(1, update_username);
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null,"Successfully Deleted");
        new Dashboard().setVisible(true);
        dispose();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void tbl_questionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_questionsMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbl_questions.getModel();
        int j = tbl_questions.getSelectedRow();
            
            question.setText(model.getValueAt(j, 0).toString());
            q1.setText(model.getValueAt(j, 1).toString());
            q2.setText(model.getValueAt(j, 2).toString());
            q3.setText(model.getValueAt(j, 3).toString());
            q4.setText(model.getValueAt(j,4).toString());
            ca.setText(model.getValueAt(j,5).toString());
            q_id.setText(model.getValueAt(j,7).toString());
            String sub = model.getValueAt(j,6).toString();
            setSubject(sub);
            btn_questionAdd.setText("Update");
            btn_questionsDelete.setVisible(true);
            
            

    }//GEN-LAST:event_tbl_questionsMouseClicked

    private void btn_questionsDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_questionsDeleteActionPerformed
        // TODO add your handling code here:
        try{
        Connection dbconn = DBconnection.connection();
        PreparedStatement pst = (PreparedStatement) dbconn.prepareStatement("delete from questions where question_no = ?");
        pst.setString(1,q_id.getText());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null,"Succesfully Deleted!");
        new Dashboard().setVisible(true);
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_btn_questionsDeleteActionPerformed
    
    public void setSubject(String sub)
    {
        if("History".equals(sub))
            {
                subject.setSelectedIndex(0);
            }
            if ("General Knowledge".equals(sub))
            {
                subject.setSelectedIndex(1);
            }
            if ("Science".equals(sub))
            {
                subject.setSelectedIndex(2);
            }
        
    }
    public void clearLabel()
    {
        lbl_question.setText("");
        lbl_q1.setText("");
        lbl_q2.setText("");
        lbl_q3.setText("");
        lbl_q4.setText("");
        lbl_ca.setText("");
        lbl_name.setText("");
        lbl_std_id.setText("");
        lbl_batch.setText("");
        lbl_section.setText("");
    }
    public boolean validation(String question, String q1, String q2, String q3, String q4, String ca)
    {
        if(question.isEmpty())
        {
            lbl_question.setText("Please Enter Question");
            return false;
        }
        if(q1.isEmpty())
        {
            lbl_q1.setText("Please Enter Option 1");
            return false;
        }
        if(q2.isEmpty())
        {
            lbl_q2.setText("Please Enter Option 2");
            return false;
        }
        if(q3.isEmpty())
        {
            lbl_q3.setText("Please Enter Option 3");
            return false;
        }
        if(q4.isEmpty())
        {
            lbl_q4.setText("Please Enter Option 4");
            return false;
        }
        if(ca.isEmpty())
        {
            lbl_ca.setText("Please Enter the Correct Answer");
            return false;
        }
        return true;
    }
    
    public boolean validation_user()
    {
        if(fname.getText().trim().isEmpty())
        {
            lbl_name.setText("Please Enter Name");
            return false;
        }
        if(txt_std_id.getText().trim().isEmpty())
        {
            lbl_std_id.setText("Please Enter Id");
            return false;
        }
        if(txt_batch.getText().trim().isEmpty())
        {
            lbl_batch.setText("Please Enter Batch");
            return false;
        }
        if(txt_section.getText().trim().isEmpty())
        {
            lbl_section.setText("Pleaase Enter Section");
            return false;
        }

            return true;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_questionAdd;
    private javax.swing.JButton btn_questionsDelete;
    private javax.swing.JButton btn_register;
    private javax.swing.JTextField ca;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_batch;
    private javax.swing.JLabel lbl_ca;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_q1;
    private javax.swing.JLabel lbl_q2;
    private javax.swing.JLabel lbl_q3;
    private javax.swing.JLabel lbl_q4;
    private javax.swing.JLabel lbl_question;
    private javax.swing.JLabel lbl_section;
    private javax.swing.JLabel lbl_std_id;
    private javax.swing.JTextField q1;
    private javax.swing.JTextField q2;
    private javax.swing.JTextField q3;
    private javax.swing.JTextField q4;
    private javax.swing.JTextField q_id;
    private javax.swing.JTextField question;
    private javax.swing.JComboBox<String> subject;
    private javax.swing.JTable tbl_questions;
    private javax.swing.JTable tbl_users;
    private javax.swing.JTextField txt_batch;
    private javax.swing.JTextField txt_section;
    private javax.swing.JTextField txt_std_id;
    // End of variables declaration//GEN-END:variables
}
