/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mcqapp;

import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.*;
import static java.util.Collections.list;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import java.util.stream.IntStream;
import javax.swing.JOptionPane;

/**
 *
 * @author Sujal
 */
public class Questions extends javax.swing.JFrame {

           static ArrayList<Integer> q_no_list = new ArrayList<Integer>();
           static ArrayList<String> questions = new ArrayList<String>();
           int i = 0,count = 0,active = 0;
           int score = 0,q_no = 0;
           String correctAnswer = "",subject = "",name = "";
    /**
     * Creates new form Questions
     */
    public Questions() {
        initComponents();
        questionSet();
        load_question();  
        setResizable(false);
    }
    
    public Questions(String subjectVar,String n){
        initComponents();
        subject = subjectVar;
        name = n;
        questionSet();
        load_question(); 
        setResizable(false);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpOptions = new javax.swing.ButtonGroup();
        lbl_q_no = new javax.swing.JLabel();
        lbl_question = new javax.swing.JLabel();
        rbtn_op1 = new javax.swing.JRadioButton();
        rbtn_op2 = new javax.swing.JRadioButton();
        rbtn_op3 = new javax.swing.JRadioButton();
        rbtn_op4 = new javax.swing.JRadioButton();
        btn_submit = new javax.swing.JButton();
        lbl_options = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_q_no.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_q_no.setText("1");

        lbl_question.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_question.setText("What is the Capital of Nepal?");

        btnGrpOptions.add(rbtn_op1);
        rbtn_op1.setText("Makawanpur");

        btnGrpOptions.add(rbtn_op2);
        rbtn_op2.setText("Kathmandu");

        btnGrpOptions.add(rbtn_op3);
        rbtn_op3.setText("Tanahun");

        btnGrpOptions.add(rbtn_op4);
        rbtn_op4.setText("Pokhara");

        btn_submit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_submit.setText("Next");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        lbl_options.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lbl_q_no, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(lbl_question, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(lbl_options, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(rbtn_op1)
                .addGap(212, 212, 212)
                .addComponent(rbtn_op2))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(rbtn_op3)
                .addGap(234, 234, 234)
                .addComponent(rbtn_op4))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(btn_submit))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lbl_q_no, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_question, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(lbl_options)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(rbtn_op1))
                    .addComponent(rbtn_op2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(rbtn_op3))
                    .addComponent(rbtn_op4))
                .addGap(3, 3, 3)
                .addComponent(btn_submit))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(null,subject);
        if(validation()){
        String answer = "";
        if(rbtn_op1.isSelected())
        {
            answer = rbtn_op1.getText();
        
        }

        else if(rbtn_op2.isSelected())
        {
            answer = rbtn_op2.getText();
        }
        else if(rbtn_op3.isSelected())
        {
            answer = rbtn_op3.getText();
        }
        else if(rbtn_op4.isSelected())
        {
            answer = rbtn_op4.getText();
        }
        
        if(answer.equals(correctAnswer))
        {
            score = score +1;
            System.out.print("Correct Answer");
            
        }
        load_question();
        btnGrpOptions.clearSelection();
        }
        
    }//GEN-LAST:event_btn_submitActionPerformed

//    private static int randomNumber(int count)
//    {
//        Random random = new Random();
//        int a = random.ints(0, count + 1).limit(1).findFirst().getAsInt();
//                return a;
//    }
    private void load_question()
    {
        try{
            q_no++;
            lbl_q_no.setText(q_no+"/10");
//            JOptionPane.showMessageDialog(null,subject);
        if(active != 0){
        Connection dbconn = DBconnection.connection();
        PreparedStatement pst = (PreparedStatement) dbconn.prepareStatement("select * from questions where subject = ?");
        pst.setString(1,subject);
        ResultSet rs = pst.executeQuery();
        while(rs.next()){
            PreparedStatement psttemp = (PreparedStatement) dbconn.prepareStatement("INSERT INTO `questionstemp`(`question`, `q1`, `q2`, `q3`, `q4`, `ca`, `subject`) VALUES (?,?,?,?,?,?,?)");
            psttemp.setString(1,rs.getString("question"));
            psttemp.setString(2,rs.getString("q1"));
            psttemp.setString(3,rs.getString("q2"));
            psttemp.setString(4,rs.getString("q3"));
            psttemp.setString(5,rs.getString("q4"));
            psttemp.setString(6,rs.getString("ca"));
            psttemp.setString(7,rs.getString("subject"));
            psttemp.executeUpdate();            
        }
        PreparedStatement pst2 = (PreparedStatement) dbconn.prepareStatement("select * from questions where question_no = ?");     
        pst2.setInt(1,q_no_list.get(i));       
        ResultSet result = pst2.executeQuery(); 
        System.out.print(q_no_list.get(i));
        i++;
        while(result.next()){
        lbl_question.setText(result.getString("question"));
        rbtn_op1.setText(result.getString("q1"));
        rbtn_op2.setText(result.getString("q2"));
        rbtn_op3.setText(result.getString("q3"));
        rbtn_op4.setText(result.getString("q4"));
        correctAnswer = result.getString("ca");
        active = active - 1;
        lbl_options.setText("");
        }
        }
        else
        {
            Connection dbconn = DBconnection.connection();
            PreparedStatement truncate = (PreparedStatement) dbconn.prepareStatement("TRUNCATE questionsTemp");
            truncate.executeUpdate();
            new answer(score,name,subject).setVisible(true);
        }
        }    
       
//        
//        for(int i =0;i<=count;i++)
//        {
//           int q_no = i;
//           pst.setInt(1,q_no);
//           
//        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }
    
    private boolean validation()
    {
        if((rbtn_op1.isSelected() == true)||(rbtn_op2.isSelected() == true)||(rbtn_op3.isSelected()==true)|| (rbtn_op4.isSelected()==true))
        {
            return true;
        }
        else
        {
            lbl_options.setText("Please Select an Option");
            return false;
        }
    }
    private void questionSet()
    {
        try{
        Connection dbconn = DBconnection.connection();
        PreparedStatement pst = (PreparedStatement) dbconn.prepareStatement("SELECT COUNT(question_no) count from questions where subject = ?");
        pst.setString(1,subject);
        ResultSet result_count = pst.executeQuery();
        while(result_count.next()){
        count = result_count.getInt("count");
        }
        
        for(int i = 0;i<count;i++)
        {

        q_no_list.add(i+1);

        Collections.shuffle(q_no_list);
        }
        if(count > 10)
        {
        active =  10;
        }
        else
        {
            active = count;
        }
        }
        catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null, e);
                } 
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Questions().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpOptions;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel lbl_options;
    private javax.swing.JLabel lbl_q_no;
    private javax.swing.JLabel lbl_question;
    private javax.swing.JRadioButton rbtn_op1;
    private javax.swing.JRadioButton rbtn_op2;
    private javax.swing.JRadioButton rbtn_op3;
    private javax.swing.JRadioButton rbtn_op4;
    // End of variables declaration//GEN-END:variables
}
